name: Build and Deploy with PR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      
      - name: Check if version bump is needed
        id: check
        run: |
          # Skip if last commit was a version bump
          if git log -1 --pretty=%B | grep -q "chore: bump version"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create version bump branch
        id: create_branch
        if: steps.check.outputs.skip == 'false'
        run: |
          branch_name=actions/version-bump-$(date +%s)
          echo "actions_branch_name=$branch_name" >> $GITHUB_OUTPUT
          git checkout -b $branch_name

      - name: Bump version
        if: steps.check.outputs.skip == 'false'
        id: version
        run: |
          npm version patch -m "chore: bump version to %s"
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Get current version
        id: current_version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/personal-website:${{ steps.current_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/personal-website:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push version branch
        if: steps.check.outputs.skip == 'false'
        run: |
          git push origin ${{ steps.create_branch.outputs.actions_branch_name }}
      
      - name: Create Pull Request
        if: steps.check.outputs.skip == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ steps.create_branch.outputs.actions_branch_name }}
          title: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          body: |
            Automated version bump to ${{ steps.version.outputs.new_version }}
            
            This PR was automatically created by GitHub Actions.
          labels: |
            automated
            version-bump
      
